web:
  image: op-frontend
  ports:
    - "8080:8080"
  environment:
    - VUE_APP_OBSERVATION_PORTAL_API_URL=https://observe.lco.global
    - VUE_APP_ARCHIVE_API_URL=https://archive-api.lco.global
    - VUE_APP_ARCHIVE_CLIENT_URL=https://archive.lco.global
    - VUE_APP_SIMBAD_SERVICE_URL=https://simbad2k.lco.global
    - VUE_APP_THUMBNAILS_SERVICE_URL=https://thumbnails.lco.global
    - INTERNAL_OBSERVATION_PORTAL_API_URL=https://observe.lco.global
