apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: obs-portal-frontend
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: obs-portal-frontend
      custom:
        buildCommand: skaffold-builder-buildx
        dependencies:
          dockerfile:
            path: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/local-dev/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
---
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: obs-portal-frontend-deps
manifests:
  kustomize:
    paths:
      - k8s/local-dev/deps/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer

